# Generated by Django 4.0.2 on 2022-03-16 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('engineering', 'خدمات مهندسی'), ('insurance', 'خدمات بیمه'), ('material', 'خدمات مصالح'), ('contracting', 'خدمات پیمانکاری')], max_length=255, null=True, verbose_name='پروژه\u200cها')),
                ('service_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('contracting_concrete', 'اجرای ساختمان بتنی'), ('contracting_excavation', 'حفاری و گودبرداری'), ('contracting_facing', 'نما و سیمان\u200cکاری'), ('contracting_gas', 'لوله\u200cکشی گاز'), ('contracting_nailing', 'نیلینگ'), ('contracting_painting', 'نقاشی'), ('contracting_piling', 'حفاری شمع'), ('contracting_plastering', 'گچ\u200cکاری'), ('contracting_plumbing', 'لوله\u200cکشی'), ('contracting_scaffolding', 'داربست'), ('contracting_steel', 'اجرای ساختمان فولادی'), ('contracting_tiling', 'کاشی\u200cکاری'), ('contracting_truss', 'سازه نگهبان خرپایی'), ('contracting_wall', 'بنایی دیوارچینی'), ('contracting_waterproofing', 'ایزوگام'), ('contracting_wiring', 'سیم\u200cکشی'), ('material_aac', 'بلوک سبک AAC'), ('material_beam', 'تیرچه\u200cی سقف'), ('material_clay', 'بلوک سفالی دیوار'), ('material_concrete', 'بتن آماده'), ('material_concrete_block', 'بلوک سیمانی یا پوکه\u200cای توخالی'), ('material_frame', 'درب و پنجره'), ('material_grains', 'شن و ماسه'), ('material_polystyrene', 'یونولیت'), ('engineering', 'مهندسی'), ('insurance_employee', 'بیمه\u200cی مسئولیت کارکنان'), ('insurance_third_party', 'بیمه\u200cی مسئولیت شخص ثالث'), ('insurance_quality', 'بیمه تضمین کیفیت')], max_length=255, null=True, verbose_name='سرویس\u200cها/خدمات')),
                ('province', models.CharField(choices=[('alborz', 'البرز'), ('ardabil', 'اردبیل'), ('east_azerbaijan', 'آذربایجان شرقی'), ('west_azerbaijan', 'آذربایجان غربی'), ('bushehr', 'بوشهر'), ('chahar_mahaal_and_bakhtiari', 'چهار محال و بختیاری'), ('fars', 'فارس'), ('gilan', 'گیلان'), ('golestan', 'گلستان'), ('hamadan', 'همدان'), ('hormozgan', 'هرمزگان'), ('ilam', 'ایلام'), ('isfahan', 'اصفحان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('north_khorasan', 'خراسان شمالی'), ('razavi_khorasan', 'خراسان رضوی'), ('south_khorasan', 'خراسان جنوبی'), ('khuzestan', 'خوزستان'), ('kohgiluyeh_and_boyer_ahmad', 'کهکیلویه و بویر احمد'), ('kurdistan', 'کردستان'), ('lorestan', 'لرستان'), ('markazi', 'مرکزی'), ('mazandaran', 'مازندران'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('semnan', 'سمنان'), ('sistan_and_baluchestan', 'سیستان و بلوچستان'), ('tehran', 'تهران'), ('yazd', 'یزد'), ('zanjan', 'زنجان')], help_text='استان محل ساختمان', max_length=27, verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد گواهی')),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='مرجع صادر کننده')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='تصویر گواهی')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='پروفایل')),
            ],
        ),
    ]
