# Generated by Django 4.0.2 on 2022-03-16 09:29

import apps.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', apps.utils.fields.JalaliAutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ عضویت')),
                ('modified', apps.utils.fields.JalaliAutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='آخرین ویرایش')),
                ('status', models.CharField(choices=[('published', 'منتشر شده'), ('draft', 'چرک\u200cنویس')], default='draft', max_length=9, verbose_name='وضعیت')),
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=10, lowercase=True, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('engineering', 'خدمات مهندسی'), ('insurance', 'خدمات بیمه'), ('material', 'خدمات مصالح'), ('contracting', 'خدمات پیمانکاری')], help_text='لطفا نوع خدمات مورد نیاز خود را جستجو و انتخاب کنید.', max_length=11, null=True, verbose_name='رسته')),
                ('service_type', models.CharField(choices=[('contracting_concrete', 'اجرای ساختمان بتنی'), ('contracting_excavation', 'حفاری و گودبرداری'), ('contracting_facing', 'نما و سیمان\u200cکاری'), ('contracting_gas', 'لوله\u200cکشی گاز'), ('contracting_nailing', 'نیلینگ'), ('contracting_painting', 'نقاشی'), ('contracting_piling', 'حفاری شمع'), ('contracting_plastering', 'گچ\u200cکاری'), ('contracting_plumbing', 'لوله\u200cکشی'), ('contracting_scaffolding', 'داربست'), ('contracting_steel', 'اجرای ساختمان فولادی'), ('contracting_tiling', 'کاشی\u200cکاری'), ('contracting_truss', 'سازه نگهبان خرپایی'), ('contracting_wall', 'بنایی دیوارچینی'), ('contracting_waterproofing', 'ایزوگام'), ('contracting_wiring', 'سیم\u200cکشی'), ('material_aac', 'بلوک سبک AAC'), ('material_beam', 'تیرچه\u200cی سقف'), ('material_clay', 'بلوک سفالی دیوار'), ('material_concrete', 'بتن آماده'), ('material_concrete_block', 'بلوک سیمانی یا پوکه\u200cای توخالی'), ('material_frame', 'درب و پنجره'), ('material_grains', 'شن و ماسه'), ('material_polystyrene', 'یونولیت'), ('engineering', 'مهندسی'), ('insurance_employee', 'بیمه\u200cی مسئولیت کارکنان'), ('insurance_third_party', 'بیمه\u200cی مسئولیت شخص ثالث'), ('insurance_quality', 'بیمه تضمین کیفیت')], max_length=25, null=True, verbose_name='نوع خدمات')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building', verbose_name='ساختمان')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ContractingProject',
            fields=[
            ],
            options={
                'verbose_name': 'درخواست پیمانکاری',
                'verbose_name_plural': 'درخواست\u200cهای پیمانکاری',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
        migrations.CreateModel(
            name='EngineeringProject',
            fields=[
            ],
            options={
                'verbose_name': 'درخواست مهندسی',
                'verbose_name_plural': 'درخواست\u200cهای مهندسی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
        migrations.CreateModel(
            name='InsuranceProject',
            fields=[
            ],
            options={
                'verbose_name': 'درخواست بیمه',
                'verbose_name_plural': 'درخواست\u200cهای بیمه',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
        migrations.CreateModel(
            name='MaterialProject',
            fields=[
            ],
            options={
                'verbose_name': 'درخواست مصالح',
                'verbose_name_plural': 'درخواست\u200cهای مصالح',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
    ]
