# Generated by Django 4.0.2 on 2022-03-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_phonenumber_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('contractor', 'پیمانکار'), ('employer', 'کارفرما')], default='employer', max_length=11, verbose_name='نقش کاربری'),
        ),
    ]
