# Generated by Django 4.0.2 on 2022-03-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractingconcreteservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingexcavationservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingfacingservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractinggasservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingnailingservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingpaintingservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingpilingservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingplasteringservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingplumbingservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingscaffoldingservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingsteelservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingtilingservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingtrussservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingwallservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingwaterproofingservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
        migrations.AlterField(
            model_name='contractingwiringservice',
            name='start',
            field=models.CharField(blank=True, help_text='مثلا: ۱۲ مهر ۱۴۰۱', max_length=100, null=True, verbose_name='تاریخ تقریبی شروع پروژه'),
        ),
    ]
