# Generated by Django 4.0.2 on 2022-03-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='description',
            new_name='general_description',
        ),
    ]
