# Generated by Django 4.0.2 on 2022-03-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_rename_finance_proposal_financcial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='completion_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='به روز وارد کنید.', null=True, verbose_name='مدت زمان تقریبی اجرای پروژه'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='price',
            field=models.PositiveBigIntegerField(help_text='به تومان وارد کنید.', verbose_name='دستمزد پیشنهادی'),
        ),
    ]
