# Generated by Django 4.0.2 on 2022-03-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_completion_time_alter_proposal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='financcial_description',
            new_name='financial_description',
        ),
    ]
