# Generated by Django 4.0.2 on 2022-03-16 09:29

import apps.utils.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', apps.utils.fields.JalaliAutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ عضویت')),
                ('modified', apps.utils.fields.JalaliAutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='آخرین ویرایش')),
                ('credit', models.IntegerField(blank=True, null=True, verbose_name='اعتبار')),
                ('unlimited', models.BooleanField(default=False, verbose_name='شامل عضویت نامحدود یکساله شهرستان\u200cها')),
                ('unlimited_tehran', models.BooleanField(default=False, verbose_name='شامل عضویت نامحدود یکساله تهران')),
                ('price', models.IntegerField(default=0, verbose_name='قابل پرداخت')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('payment_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
