from django.db import models


class Provinces(models.TextChoices):
    alborz = "alborz", "البرز"
    ardabil = "ardabil", "اردبیل"
    east_azerbaijan = "east_azerbaijan", "آذربایجان شرقی"
    west_azerbaijan = "west_azerbaijan", "آذربایجان غربی"
    bushehr = "bushehr", "بوشهر"
    chahar_mahaal_and_bakhtiari = "chahar_mahaal_and_bakhtiari", "چهار محال و بختیاری"
    fars = "fars", "فارس"
    gilan = "gilan", "گیلان"
    golestan = "golestan", "گلستان"
    hamadan = "hamadan", "همدان"
    hormozgan = "hormozgan", "هرمزگان"
    ilam = "ilam", "ایلام"
    isfahan = "isfahan", "اصفهان"
    kerman = "kerman", "کرمان"
    kermanshah = "kermanshah", "کرمانشاه"
    north_khorasan = "north_khorasan", "خراسان شمالی"
    razavi_khorasan = "razavi_khorasan", "خراسان رضوی"
    south_khorasan = "south_khorasan", "خراسان جنوبی"
    khuzestan = "khuzestan", "خوزستان"
    kohgiluyeh_and_boyer_ahmad = "kohgiluyeh_and_boyer_ahmad", "کهکیلویه و بویر احمد"
    kurdistan = "kurdistan", "کردستان"
    lorestan = "lorestan", "لرستان"
    markazi = "markazi", "مرکزی"
    mazandaran = "mazandaran", "مازندران"
    qazvin = "qazvin", "قزوین"
    qom = "qom", "قم"
    semnan = "semnan", "سمنان"
    sistan_and_baluchestan = "sistan_and_baluchestan", "سیستان و بلوچستان"
    tehran = "tehran", "تهران"
    yazd = "yazd", "یزد"
    zanjan = "zanjan", "زنجان"
